// AUTO-GENERATED by scripts/embed-profiles.ts — do not edit manually.
// Data source: profiles/*.yaml. Regeneration: bun run embed:profiles.
/** Embedded installer profiles (P8.1): name → YAML text. */
export const EMBEDDED_PROFILES_YAML: Record<string, string> = {
  "base": "name: base\ndescription: \"Base system: SSH, sudo, basic utilities\"\npackages:\n  - sudo\n  - openssh-server\n  - curl\n  - ca-certificates\n  - less\n  - htop\nservices:\n  - ssh\ncommands:\n  - cmd: systemctl enable ssh\n    description: Enable SSH service",
  "desktop": "name: desktop\ndescription: XFCE desktop on top of base\nextends: base\npackages:\n  - xorg\n  - xfce4\n  - xfce4-goodies\n  - lightdm\n  - network-manager\nservices:\n  - lightdm\n  - NetworkManager\ncommands:\n  - cmd: systemctl set-default graphical.target\n    description: Boot into graphical mode",
  "dev": "name: dev\ndescription: Developer tools on top of base\nextends: base\npackages:\n  - build-essential\n  - git\n  - python3\n  - python3-pip\n  - nodejs\n  - npm",
  "server": "name: server\ndescription: Server system on top of base\nextends: base\npackages:\n  - nginx\n  - ufw\n  - fail2ban\n  - unattended-upgrades\nservices:\n  - nginx\n  - ufw\n  - fail2ban\ncommands:\n  - cmd: ufw default deny incoming\n    description: Deny incoming connections by default\n    optional: true",
};
