// AUTO-GENERATED by scripts/embed-profiles.ts — не редактировать вручную.
// Источник данных: profiles/*.yaml. Регенерация: bun run embed:profiles.
/** Встроенные профили установщика (P8.1): имя → текст YAML. */
export const EMBEDDED_PROFILES_YAML: Record<string, string> = {
  "base": "name: base\ndescription: \"Базовая система: SSH, sudo, базовые утилиты\"\npackages:\n  - sudo\n  - openssh-server\n  - curl\n  - ca-certificates\n  - less\n  - htop\nservices:\n  - ssh\ncommands:\n  - cmd: systemctl enable ssh\n    description: Автозапуск SSH",
  "desktop": "name: desktop\ndescription: Рабочий стол XFCE на базе base\nextends: base\npackages:\n  - xorg\n  - xfce4\n  - xfce4-goodies\n  - lightdm\n  - network-manager\nservices:\n  - lightdm\n  - NetworkManager\ncommands:\n  - cmd: systemctl set-default graphical.target\n    description: Загрузка в графический режим",
  "dev": "name: dev\ndescription: Инструменты разработчика на базе base\nextends: base\npackages:\n  - build-essential\n  - git\n  - python3\n  - python3-pip\n  - nodejs\n  - npm",
  "server": "name: server\ndescription: Серверная система на базе base\nextends: base\npackages:\n  - nginx\n  - ufw\n  - fail2ban\n  - unattended-upgrades\nservices:\n  - nginx\n  - ufw\n  - fail2ban\ncommands:\n  - cmd: ufw default deny incoming\n    description: Закрыть входящие подключения по умолчанию\n    optional: true",
};
