import { mkdirSync, readdirSync, readFileSync, writeFileSync } from "node:fs";
import { dirname, join } from "node:path";

/** Directory with the source YAML profiles. */
const PROFILES_DIR = join(import.meta.dir, "..", "profiles");
/** Output TS module with the embedded profiles (P8.1). */
const OUT_FILE = join(import.meta.dir, "..", "src", "profiles", "embedded-data.generated.ts");

const HEADER = [
  "// AUTO-GENERATED by scripts/embed-profiles.ts — do not edit manually.",
  "// Data source: profiles/*.yaml. Regeneration: bun run embed:profiles.",
  "/** Embedded installer profiles (P8.1): name → YAML text. */",
  "export const EMBEDDED_PROFILES_YAML: Record<string, string> = {",
];

/** Generates the TS module with embedded profiles from the YAML files of profiles/. */
function main(): void {
  const files = readdirSync(PROFILES_DIR)
    .filter((file) => /\.(yaml|yml)$/.test(file))
    .sort();

  if (files.length === 0) {
    throw new Error(`No YAML profiles in ${PROFILES_DIR}`);
  }

  const entries = files.map((file) => {
    const name = file.replace(/\.(yaml|yml)$/, "");
    const text = readFileSync(join(PROFILES_DIR, file), "utf8").trimEnd();
    return `  ${JSON.stringify(name)}: ${JSON.stringify(text)},`;
  });

  const content = [...HEADER, ...entries, "};\n"].join("\n");
  mkdirSync(dirname(OUT_FILE), { recursive: true });
  writeFileSync(OUT_FILE, content);
  console.log(`Generated: ${OUT_FILE} (${files.length} profiles)`);
}

main();
