import { mkdirSync, readdirSync, readFileSync, writeFileSync } from "node:fs";
import { dirname, join } from "node:path";

/** Каталог с исходными YAML-профилями. */
const PROFILES_DIR = join(import.meta.dir, "..", "profiles");
/** Выходной TS-модуль со встроенными профилями (P8.1). */
const OUT_FILE = join(import.meta.dir, "..", "src", "profiles", "embedded-data.generated.ts");

const HEADER = [
  "// AUTO-GENERATED by scripts/embed-profiles.ts — не редактировать вручную.",
  "// Источник данных: profiles/*.yaml. Регенерация: bun run embed:profiles.",
  "/** Встроенные профили установщика (P8.1): имя → текст YAML. */",
  "export const EMBEDDED_PROFILES_YAML: Record<string, string> = {",
];

/** Генерирует TS-модуль со встроенными профилями из YAML-файлов каталога profiles/. */
function main(): void {
  const files = readdirSync(PROFILES_DIR)
    .filter((file) => /\.(yaml|yml)$/.test(file))
    .sort();

  if (files.length === 0) {
    throw new Error(`Нет YAML-профилей в ${PROFILES_DIR}`);
  }

  const entries = files.map((file) => {
    const name = file.replace(/\.(yaml|yml)$/, "");
    const text = readFileSync(join(PROFILES_DIR, file), "utf8").trimEnd();
    return `  ${JSON.stringify(name)}: ${JSON.stringify(text)},`;
  });

  const content = [...HEADER, ...entries, "};\n"].join("\n");
  mkdirSync(dirname(OUT_FILE), { recursive: true });
  writeFileSync(OUT_FILE, content);
  console.log(`Сгенерировано: ${OUT_FILE} (${files.length} профилей)`);
}

main();
